# Supabase Configuration for Rezzmo Backend

[api]
enabled = true
port = 54321
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600

[storage]
enabled = true
file_size_limit = 52428800  # 50MB
